FROM node:lts
RUN mkdir /app
ADD front/ /app/front/
ADD platform/ /app/platform/
WORKDIR /app/platform/
RUN echo "8kHmDagLEh65B9Kq" | yarn install
RUN NODE_ENV=development yarn build
EXPOSE 1337 80 443
CMD SOURCE_BOOTSTRAP=true NODE_ENV=development yarn start
